apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: appr_input_params
on:
  workflow_dispatch:
jobs:
  ask-now:
    with:
      approvers: 0a808e26-f884-11ec-aa0a-42010a83ae55
      disallowLaunchByUser: false
      instructions: Test instructions here
      # debug: true
      approvalInputs: |
        str_req_def:
          type: string
          default: def1
          required: true
        str_opt_def:
          type: string
          default: def2
        bool_req_def:
          type: boolean
          default: true
          required: true
        bool_no_req_def_tr:
          type: boolean
          default: true
          description: a boolean input
        bool_no_req_def_fa:
          type: boolean
          default: false
          description: a boolean input  
        num_req_def:
          type: number
          default: 9999
          required: true
        num_opt_def:
          type: number
          default: 1234
        ch_opt_def:
          type: choice
          options:
            - op1
            - op2
          default: op2
        str_opt_no_def:
          type: string
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/.cloudbees/testing/custom-job.yml
  print_outputs:
    steps:
      - name: Print manual approval output params
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Output from custom job:"
          echo "comments: ${{ needs.ask-now.outputs.comments }}"
          echo "approvalInputValues: ${{ needs.ask-now.outputs.approvalInputValues }}"
          echo "str_req_def: ${{fromJSON(needs.ask-now.outputs.approvalInputValues).str_req_def}}"
          echo "bool_req_def: ${{fromJSON(needs.ask-now.outputs.approvalInputValues).bool_req_def}}"
          echo "num_req_def: ${{fromJSON(needs.ask-now.outputs.approvalInputValues).num_req_def}}"
          echo "ch_opt_def: ${{fromJSON(needs.ask-now.outputs.approvalInputValues).ch_opt_def}}"
    needs: ask-now
