apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Kaniko workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://eclipse-temurin:21-alpine
        shell: sh
        run: |
          ./gradlew clean build;
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ vars.DOCKERHUB_UNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build container image with Kaniko (Kush)
        uses: cloudbees-io/kaniko/.cloudbees/testing
        with:
          destination: docker.io/kushicp/kanikotest/docker-demo:0.0.1-SNAPSHOT
          verbosity: DEBUG
          send-artifact-info: true
