apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: LabelArtifactVersion
on:
  workflow_dispatch:

jobs:
  success_add_labels_to_artifact_ver:
    steps:
      - name: success_add_labels_to_artifact_ver
        uses: cloudbees-io/label-artifact-version@CBP-15766
        with:
          artifact-id: "79d1fa4d-b7bf-47bf-b767-9879b5223ae9"
          labels: "Added, new labels"
          operation: "ADD"
