apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: LabelArtifactVersion
on:
  workflow_dispatch:

jobs:
  success_add_labels_to_artifact_ver:
    steps:
      - name: success_add_labels_to_artifact_ver
        uses: cloudbees-io/label-artifact-version@CBP-15766
        with:
          artifact-id: "e598175c-e2e5-4bb9-a440-65188213bfaa" # python-hello-world
          labels: "Added, new labels"
          operation: "ADD"
