apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: man appr input params
on:
  workflow_dispatch:
jobs:
  ask-now:
    with:
      approvers: 0a808e26-f884-11ec-aa0a-42010a83ae55
      disallowLaunchByUser: false
      instructions: Test instructions here
      approvalInputs: |
        str_req_def:
          type: string
          default: def1
          required: true
        str_no_req_def:
          type: string
          default: def2
        bool_req_def:
          type: boolean
          default: true
          required: true
        bool_no_req_def:
          type: boolean
          default: true
        bool_req_no_def:
          type: boolean
          default: false
          required: true
        bool_no_req_no_def:
          type: boolean
          default: false
        num_no_req_def:
          type: number
          default: 9999
        num_no_req_no_def:
          type: number
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@CBP-8428-export_input_output
  print_outputs:
    steps:
      - name: Print manual approval output params
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Output from custom job:"
          echo "str_req_def: ${{ ${{needs.ask-now.outputs.str_req_def}}"
          echo "str_no_req_def: ${{needs.ask-now.outputs.str_no_req_def}}"
          echo "bool_req_def: ${{needs.ask-now.outputs.bool_req_def}}"
          echo "bool_no_req_def: ${{needs.ask-now.outputs.bool_no_req_def}}"
          echo "bool_req_no_def: ${{needs.ask-now.outputs.bool_req_no_def}}"
          echo "bool_no_req_no_def: ${{needs.ask-now.outputs.bool_no_req_no_def}}"
          echo "num_no_req_def: ${{needs.ask-now.outputs.num_no_req_def}}"
          echo "num_no_req_no_def: ${{needs.ask-now.outputs.num_no_req_no_def}}"
    needs: ask-now
