apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: getArtifactDetails
on:
  workflow_dispatch:
jobs:
  getDetails:
    steps:
      - name: getArtifactDetails
        uses: cloudbees-io/get-artifact-details@CBP-20956
        with:
          artifact-id: ea07033d-3008-40ec-9e50-a0efce7493d8
  print_details:
    steps:
      - name: Print artifact details output 
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Output from getArtifactDetails: ${{ needs.getDetails.outputs }}"
          echo "name: ${{ needs.getDetails.outputs.name }}"
          echo "version: ${{ needs.getDetails.outputs.version }}"
          echo "url: ${{ needs.getDetails.outputs.url }}"
          echo "digest: ${{ needs.getDetails.outputs.digest }}"
    needs: getDetails