apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: getArtifactDetails
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: getArtifactDetails
        uses: cloudbees-io/get-artifact-details@CBP-20956
        with:
          artifact-id: ea07033d-3008-40ec-9e50-a0efce7493d8
