apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publishAndDeployArtifact
on:
  workflow_dispatch:
jobs:
  deployArtifact:
    steps:
      - name: Register deployed artifact
        with:
          artifact-id: ea07033d-3008-40ec-9e50-a0efce7493d8
          target-environment: Test_env
          labels: 27603-TestAdd
        uses: cloudbees-io/register-deployed-artifact@v2
        id: deployArtifact
