apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterBuildArtifact
on:
  workflow_dispatch:
jobs:
  buildArtRegTest:
    steps:
      - id: registerBuildArtifact
        name: catalog action test
        with:
          version: "14.9"
          url: docker.io/myapp/kcpImg14:14.0.9
          digest: d149
          labels:  "lbl1"
          name: kcpBuildRegister 149
        uses: cloudbees-io/register-build-artifact@CBP-15450
      - name: Artifact Id output
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Output param: ${{ steps.registerBuildArtifact.outputs.artifact-id }}"