apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publishAndDeployArtifact
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: Test_env
        required: true
jobs:
  publishArtifact:
    environment: ${{ inputs.env }}
    steps:
      - name: Register deployed artifact
        id: deployArtifact
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: testArtifactRegister2
          version: 2.0.0
          url: docker.io/MyKcpApp/testArtifactRegister:2.0.0
          digest: sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b36342
  deployArtifact1:
    environment: ${{ inputs.env }}
    steps:
      - name: Register deployed artifact
        with:
          version: 2.0.0
          url: docker.io/MyKcpApp/testArtifactRegister:2.0.0
          digest: sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b36342
          action-name: testArtifactRegister2
        uses: cloudbees-io/register-deployed-artifact@main
        id: deployArtifact1
    needs:
      - publishArtifact
  deployArtifact2:
    environment: kcp-env
    steps:
      - name: Register deployed artifact
        with:
          version: 2.0.0
          url: docker.io/MyKcpApp/testArtifactRegister:2.0.0
          digest: sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b36342
          action-name: testArtifactRegister2
        uses: cloudbees-io/register-deployed-artifact@main
        id: deployArtifact2
    needs:
      - deployArtifact1
