apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterBuildArtifact

on:
  workflow_dispatch:
jobs:
  build:
    steps:
        - name: '[\"aL1\",\"aL2\",\"aL3\"]'
          uses: cloudbees-io/register-build-artifact@CBP-14025
          with:
            name: "kcpBldRegister 4"
            version: "4.0.0"
            url: "docker.io/myapp/kcpBldImg:4.0.4"
            digest: "d4"
            labels:  '[\"aL1\",\"aL2\",\"aL3\"]'
    # invalid character '\\\\'
      #- name: '["aL1","aL2","aL3"]'
      #  uses: cloudbees-io/register-build-artifact@CBP-14025
      #  with:
      #    name: "kcpBldRegister 3"
      #    version: "3.0.0"
      #    url: "docker.io/myapp/kcpBldImg:3.0.3"
      #    digest: "d3"      
      #    labels:  '["aL1","aL2","aL3"]'
      # invalid Failed
        
      # "message":"label cannot be empty or whitespace"
      # - name: empty label and whitespaces
      #   uses: cloudbees-io/register-build-artifact@CBP-14025
      #   with:
      #     name: "kcpBldRegister 5"
      #     version: "5.0.0"
      #     url: "docker.io/myapp/kcpBldImg:5.0.5"
      #     digest: "d5"
      #     labels: " ,       Label with space     , aLabel!!    "
      # "message":"label cannot be empty or whitespace"
      # - name: empty labels separated by ,
      #   uses: cloudbees-io/register-build-artifact@CBP-14025
      #   with:
      #     name: "kcpBldRegister 6"
      #     version: "6.0.0"
      #     url: "docker.io/myapp/kcpBldImg:6.0.6"
      #     digest: "d6"
      #     labels: " , "
        - name: apos label
          uses: cloudbees-io/register-build-artifact@CBP-14025
          with:
            name: "kcpBldRegister 7"
            version: "7.0.0"
            url: "docker.io/myapp/kcpBldImg:7.0.7"
            digest: "d7"
            labels: "Hi'Label , asda"
      # "message":"label cannot be empty or whitespace"
      # - name: single whitespace label
      #   uses: cloudbees-io/register-build-artifact@CBP-14025
      #   with:
      #     name: "kcpBldRegister 8"
      #     version: "8.0.0"
      #     url: "docker.io/myapp/kcpBldImg:8.0.8"
      #     digest: "d8"
      #     labels: "   "