apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publishAndDeployArtifact
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
jobs:
  publishArtifact:
    steps:
      - name: Register published artifact
        id: publish
        uses: cloudbees-io/register-published-artifact@v1
        with:
          name: "testArtifactRegister"
          version: "1.1.0"
          url: "docker.io/MyKcpApp/testArtifactRegister:1.1.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3644"

  deployArtifact:
    environment: ${{ inputs.environment }}
    steps:
      - name: Inform system that an artifact version was deployed
        uses: cloudbees-io/register-deployed-artifact@main 
        with:
          name: "${{ publishArtifact.steps.publish.name }}"
          version: "${{ publishArtifact.steps.publish.version }}"
          url: "docker.io/MyKcpApp/${{ publishArtifact.steps.publish.name }}:${{ publishArtifact.steps.publish.version }}" # Remove this once Action updated
          #target-environment: "${{ inputs.environment }}"