apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterBuildArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: label1, Label with space, aLabel!!
        uses: cloudbees-io/register-build-artifact@CBP-12151
        with:
          name: "artRegister 1"
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3609"
          labels: "label1, Label with space, aLabel!!"
      - name: "['aLabel1', 'aLabel2', 'aLabel3']"
        uses: cloudbees-io/register-build-artifact@CBP-12151
        with:
          name: "artRegister 2"
          version: "2.0.0"
          url: "docker.io/myapp/myimg:2.0.0"
          digest: ""
          labels: "['aLabel1', 'aLabel2', 'aLabel3']"
      - name: '["aL1","aL2","aL3"]'
        uses: cloudbees-io/register-build-artifact@CBP-12151
        with:
          name: "artRegister 3"
          version: "3.0.0"
          url: "docker.io/myapp/myimg:3.0.0"
          digest: ""
          labels:  '["aL1","aL2","aL3"]'
      - name: '[\"aL1\",\"aL2\",\"aL3\"]'
        uses: cloudbees-io/register-build-artifact@CBP-12151
        with:
          name: "artRegister 4"
          version: "4.0.0"
          url: "docker.io/myapp/myimg:4.0.0"
          digest: ""
          labels:  '[\"aL1\",\"aL2\",\"aL3\"]'
      - name: empty label and whitespaces
        uses: cloudbees-io/register-build-artifact@CBP-12151
        with:
          name: "artRegister 5"
          version: "5.0.0"
          url: "docker.io/myapp/myimg:5.0.0"
          digest: ""
          labels: " ,       Label with space     , aLabel!!    "
      - name: empty labels separated by ,
        uses: cloudbees-io/register-build-artifact@CBP-12151
        with:
          name: "artRegister 6"
          version: "6.0.0"
          url: "docker.io/myapp/myimg:6.0.0"
          digest: ""
          labels: " , "
      - name: single label
        uses: cloudbees-io/register-build-artifact@CBP-12151
        with:
          name: "artRegister 7"
          version: "7.0.0"
          url: "docker.io/myapp/myimg:7.0.0"
          digest: ""
          labels: "HiLabel"
      - name: single whitespace label
        uses: cloudbees-io/register-build-artifact@CBP-12151
        with:
          name: "artRegister 7"
          version: "7.0.0"
          url: "docker.io/myapp/myimg:7.0.0"
          digest: ""
          labels: "   "